from pathlib import Path

##############################
# Configuration
##############################
configfile: "config/config.yaml"


bioproject = Path(config.get("bioproject", config.get("project", "UnknownProject")))
project_dir = Path("work") / bioproject

include: "rules/common.smk"

intervals = group_intervals()
reference_basename = get_reference_basename()

##############################
# Path variables
##############################
pathvars:
    bioproject = str(bioproject),
    ref = "ref",
    resources = "resources",
    results = "results",
    work = "work",


##############################
# Default target
##############################
samples = config.get("samples", sampleinfo.loc[:, "SampleName"].tolist())
try:
    i = sampleinfo.loc[:, "SampleName"].isin(samples)
    sampleinfo = sampleinfo.loc[i, :]
except:
    pass

# Wildcard constraints
wildcard_constraints:
    allsites="(.allsites|)",
    callmode="raw|bqsr",
    callset="all",
    ivl="(" + "|".join(intervals.keys()) + ")",
    mode="(.g|)",
    samplename="(" + "|".join(sampleinfo.SampleName.values) + ")",

ALL = {
    "aa": "<results>/ancestral_allele/all.vcf.gz",
}

sampleinfo_file = Path("sampleinfo.csv")

if not sampleinfo_file.exists():
    logger.warning(f"Sampleinfo file {sampleinfo_file} does not exist.")
    logger.info("Rerun workflow once sampleinfo is generated.")
    ALL = {"sampleinfo": str(sampleinfo_file)}



rule all:
    input:
        **ALL,
    default_target: True


##############################
# Rules
##############################
include: "rules/datasources.smk"
include: "rules/sampleinfo.smk"
include: "rules/sra.smk"
include: "rules/bwa.smk"
include: "rules/gatk.smk"
include: "rules/ref.smk"
include: "rules/variation.smk"
include: "rules/phasing.smk"

onstart:
    print("Starting workflow...")


onerror:
    print("An error occurred during the workflow execution.")


onsuccess:
    print("Workflow completed successfully!")
    if len(samples) == 0:
        print("Generated sampleinfo: rerun to complete workflow")
