from pathlib import Path

##############################
# Configuration
##############################
configfile: "config/config.yaml"


bioproject = Path(config.get("bioproject", config.get("project", "UnknownProject")))
project_dir = Path("work") / bioproject

include: "rules/common.smk"


##############################
# Path variables
##############################
pathvars:
    project = str(bioproject),
    ref = str(bioproject / "ref"),


##############################
# Default target
##############################
i = sampleinfo.loc[:, "SampleAlias"].isin(config["samples"])
sampleinfo = sampleinfo.loc[i, :]

# Wildcard constraints
wildcard_constraints:
    callmode="raw|bqsr",
    callset="all",
    samplealias="(" + "|".join(sampleinfo.SampleAlias.values) + ")",


ALL = {
    "sampleinfo": bioproject / "sampleinfo.csv",
    #"bwa_index": bioproject / "ref" / config["reference"],
    # "bwa": expand(
    #     "<project>/bam_bwa_srr/{samplealias}/{srrun}.sort.cram",
    #     zip,
    #     srrun=sampleinfo["Run"],
    #     samplealias=sampleinfo["SampleAlias"],
    # ),
    "gatk_filter": expand(
        "<project>/gatk-hc-filter-bqsr/{samplealias}.g.vcf.gz",
        samplealias=sampleinfo["SampleAlias"],
    ),
    "gatk_cram": expand(
        "<project>/gatk-bqsr-cram/{samplealias}.cram",
        samplealias=sampleinfo["SampleAlias"],
    ),
    "gatk_genotype": "<project>/gatk-genotype-gvcf-bqsr/all.allsites.vcf.gz",
}


rule all:
    input:
        **ALL,
    default_target: True


##############################
# Rules
##############################
include: "rules/datasources.smk"
include: "rules/sampleinfo.smk"
include: "rules/sra.smk"
include: "rules/bwa.smk"
include: "rules/gatk.smk"
include: "rules/ref.smk"


onstart:
    print("Starting workflow...")


onerror:
    print("An error occurred during the workflow execution.")


onsuccess:
    print("Workflow completed successfully!")
