from pathlib import Path

##############################
# Configuration
##############################
configfile: "config/config.yaml"


bioproject = Path(config.get("bioproject", config.get("project", "UnknownProject")))
project_dir = Path("work") / bioproject

include: "rules/common.smk"

intervals = group_intervals()
if len(intervals) == 0:
    raise ValueError("No intervals defined in the configuration file.")
reference_basename = get_reference_basename()

##############################
# Path variables
##############################
pathvars:
    bioproject = str(bioproject),
    ref = "ref",
    resources = "resources",
    results = "results",
    scripts = "scripts",
    work = "work",


##############################
# Default target
##############################
samples = config.get("samples", sampleinfo.loc[:, "SampleName"].tolist())
try:
    i = sampleinfo.loc[:, "SampleName"].isin(samples)
    sampleinfo = sampleinfo.loc[i, :]
except:
    pass

chromosomes = sorted(list(
    set([
        iv.chrom for ivlist in intervals.values() for iv in ivlist
    ])
))

# Wildcard constraints
wildcard_constraints:
    allsites="(.allsites|)",
    callmode="raw|bqsr",
    callset="all",
    chrom="(" + "|".join(chromosomes) + ")",
    ivl="(" + "|".join(intervals.keys()) + ")",
    mode="(.g|)",
    samplename="(" + "|".join(sampleinfo.SampleName.values) + ")",

ALL = {
    "tsdate": expand("<results>/tsinfer/all.{chrom}.dated.trees", chrom=chromosomes),
}

sampleinfo_file = Path("sampleinfo.csv")

if not sampleinfo_file.exists():
    logger.warning(f"Sampleinfo file {sampleinfo_file} does not exist.")
    logger.info("Rerun workflow once sampleinfo is generated.")
    ALL = {"sampleinfo": str(sampleinfo_file), "index": os.path.join("ref", config["reference"] + ".fai")}



rule all:
    input:
        **ALL,
    default_target: True


##############################
# Rules
##############################
include: "rules/datasources.smk"
include: "rules/sampleinfo.smk"
include: "rules/sra.smk"
include: "rules/bwa.smk"
include: "rules/gatk.smk"
include: "rules/ref.smk"
include: "rules/variation.smk"
include: "rules/phasing.smk"
include: "rules/tsinfer.smk"

onstart:
    print("Starting workflow...")


onerror:
    print("An error occurred during the workflow execution.")


onsuccess:
    print("Workflow completed successfully!")
    if len(samples) == 0:
        print("Generated sampleinfo: rerun to complete workflow")
