[workspace]
authors = ["Per Unneberg <per.unneberg@scilifelab.se>"]
channels = ["conda-forge", "bioconda"]
description = "Task helpers and binary package dependencies for bioprojarg"
name = "bioprojarg"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[tasks._snakemake]
args = [
  { "arg" = "profile", "default" = "profiles/local" },
  { "arg" = "config", "default" = "config/config.yaml" },
]
cmd = "snakemake --directory work --profile {{profile}} --configfile {{config}}"

[dependencies]
python = ">=3.13.11,<3.15"
conda = ">=25.11.1,<26"

[pypi-dependencies]
bioprojarg = { path = ".", editable = true }

[feature.snakemake.dependencies]
snakemake = ">=9.14"
snakemake-storage-plugin-http = "*"
pulp = ">=2.8.0,<3"

[feature.textutils.dependencies]
csvtk = "*"
docx2txt = "*"
qsv = "*"

[feature.sratools.dependencies]
sra-tools = "*"
entrez-direct = "*"

[feature.bwa.dependencies]
bwa = "*"
samtools = "*"

[feature.test.dependencies]
pytest = "*"

[feature.test.tasks.test]
depends-on = [
  { "task" = "_snakemake", "environment" = "full", "args" = [
    { config = "config/config.test.yaml" },
  ] },
]

[feature.test.tasks.dry]
cmd = "snakemake --directory work --profile profiles/local --configfile config/config.test.yaml -n -p -F"

[feature.test.tasks.full]
depends-on = [{ task = "_snakemake", environment = "full" }]

[feature.lint.dependencies]
python = "*"
pre-commit = "*"
pre-commit-hooks = "*"
ruff = "*"
typos = "*"
actionlint = "*"
go-shfmt = "*"
taplo = "*"
pylint = "*"
snakefmt = "*"

[feature.lint.tasks]
actionlint = { cmd = "actionlint", env = { SHELLCHECK_OPTS = "-e SC2086" } }
lint = { cmd = "pre-commit run --hook-stage=manual", description = "Run all linters and formatters on staged code" }
lintall = { cmd = "pre-commit run --all-files --hook-stage=manual", description = "Run all linters and formatters on all code" }
pre-commit-install = "pre-commit install --install-hooks -t=pre-commit -t=pre-push"
pre-commit-install-minimal = "pre-commit install -t=pre-commit"
pre-commit-run = "pre-commit run --all-files"
ruff-format = "ruff format --force-exclude"
ruff-lint = "ruff check --fix --exit-non-zero-on-fix --force-exclude"
shell-format = "shfmt --write --indent=4 --simplify --binary-next-line"
toml-format = { cmd = "taplo fmt", env = { RUST_LOG = "warn" } }
toml-lint = "taplo lint --verbose **/pyproject.toml"
typecheck-python = "mypy"
typos = "typos --write-changes --force-exclude"

[feature.gatk4.dependencies]
gatk4 = "*"
picard = "*"
r-ggplot2 = ">=4.0.1,<5"
r-gplots = ">=3.3.0,<4"
r-gsalib = ">=2.2.1,<3"

[environments]
snakemake = { features = ["snakemake"], solve-group = "default" }
sratools = { features = ["sratools", "textutils"], solve-group = "default" }
textutils = { features = ["textutils"], solve-group = "default" }
full = { features = [
  "bwa",
  "gatk4",
  "snakemake",
  "sratools",
  "test",
  "textutils",
], solve-group = "default" }
lint = { features = ["snakemake", "lint"], solve-group = "default" }
