[project]
name = "bioprojarg"
dynamic = ["version"]
authors = [{ name = "Per Unneberg", email = "per.unneberg@nbis.se" }]
maintainers = [{ name = "Per Unneberg", email = "per.unneberg@nbis.se" }]
description = "Snakemake ARG inference workflow that runs on ENA Bioproject info"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "GNU GPLv3+" }
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3 :: Only",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Development Status :: 1 - Planning",
  "Environment :: Other Environment",
  "Intended Audience :: Science/Research",
  "Operating System :: POSIX",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
]
keywords = [
  "population genetics",
  "tree sequence",
  "ancestral recombination graph",
  "workflow",
  "snakemake",
]
dependencies = ["click>=8.0"]

[build-system]
requires = ["hatchling", "hatch-vcs"]
buld-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.hooks.vcs]
version-file = "src/bioprojarg/_version.py"

[tool.hatch.build.targets.wheel]
packages = ["src/bioprojarg"]

[project.scripts]
bioprojarg = "bioprojarg.cli:cli"
