# -*- yaml -*-
restart-times: 0
keep-going: true
max-status-checks-per-second: 10
latency-wait: 60
use-envmodules: false
use-conda: false
rerun-triggers: mtime
rerun-incomplete: true
cores: 15
notemp: false

set-threads:
  beagle_phase: 15
  gatk_haplotypecaller_intervals: 3

set-resources:
  beagle_phase:
    mem_mb: 40000
  gatk_base_recalibrator:
    mem_mb: 8000
