bioproject: PRJNA549183
sraruninfo:
  filter: "librarystrategy=='WGS' and samplename!='Assembly Plant'"
species: Mimulus aurantiacus
samplesheet:
  url: https://doi.org/10.1371/journal.pbio.3000391.s003
  script: ../scripts/make_test_samplesheet.sh
sampleinfo_script: ../scripts/make_test_sampleinfo.sh

datasources:
  ref/M_aurantiacus_v1_splitline_ordered.fasta: http://mimubase.org/FTP/Genomes/Maurantiacus_v1.0/M_aurantiacus_v1_splitline_ordered.fasta
  ref/MAUR_annotation_functional_submission.gff: http://mimubase.org/FTP/Genomes/Maurantiacus_v1.0/MAUR_annotation_functional_submission.gff

# Reference is located in ref/ and must be declared in datasources
reference: M_aurantiacus_v1_splitline_ordered.fasta
regions:
  - LG4:10000000-14000000
# Samples
samples:
  - PUN-R-ELF
  - PUN-R-JMC
  - PUN-Y-INJ
  - PUN-Y-BCRD
  - CLV_4
outgroup_populations:
  - clevelandii

min_interval_length: 1000000
max_interval_length: 3000000
interval_batch_size: 5000000

# From Stankowski et al. 2019
mutation_rate: 1.5e-8
recombination_rate: 1.5e-8

tsinfer:
  sampleinfo_columns: Sample,Population,Latitude,Longitude,SampleName,AuthorSample
  populations_columns: Population,Taxon,ScientificName
