bioproject: PRJNA549183
sraruninfo:
  filter: "librarystrategy=='WGS' and samplename!='Assembly Plant'"
species: Mimulus aurantiacus
samplesheet:
  url: https://doi.org/10.1371/journal.pbio.3000391.s003
  script: ../scripts/make_test_samplesheet.sh
sampleinfo_script: ../scripts/make_test_sampleinfo.sh

datasources:
  ref/M_aurantiacus_v1_splitline_ordered.fasta: http://mimubase.org/FTP/Genomes/Maurantiacus_v1.0/M_aurantiacus_v1_splitline_ordered.fasta
  ref/MAUR_annotation_functional_submission.gff: http://mimubase.org/FTP/Genomes/Maurantiacus_v1.0/MAUR_annotation_functional_submission.gff

# Reference is located in ref/ and must be declared in datasources
reference: M_aurantiacus_v1_splitline_ordered.fasta

# Samples
samples:
  - ARI-159_83
