$schema: "https://json-schema.org/draft/2020-12/schema"

description: Bioprojarg snakemake configuration file schema

type: object

properties:
  bioproject:
    description: ENA bioproject name
    type: string
    pattern: "[^ ]+"
  interval_batch_size:
    description: >-
      Size of interval batch.
    type: integer
  min_interval_length:
    description: >-
      Minimum interval length. Will remove contigs shorter than this
      number.
    type: integer
  max_interval_length:
    description: >-
      Maximum interval length. Will split contigs in
      ceil(contig_length / min_interval_length) equal parts.
    type: integer
  mutation_rate:
    description: Mutation rate per base pair per generation
    type: number
  outgroup_populations:
    description: Outgroup populations for ancestral allele determination
    type: array
    items:
      type: string
  project:
    description: Project name
    type: string
    pattern: "[^ ]+"
  recombination_rate:
    description: Recombination rate
    type: number
  recombination_rate_map:
    description: Recombination rate map
    type: string
    format: uri
  # Possibly turn into object (uri, name)
  reference:
    description: Path to reference file
    type: string
    format: uri
  regions:
    description: List of regions
    type: array
    items:
      type: string
  samples:
    description: List of samples
    type: array
    items:
      type: string
  sampleinfo_script:
    description: Script to generate sampleinfo file from SraRunInfo and samplesheet
    type: string
    format: uri
  samplesheet:
    description: Samplesheet with metadata on samples
    type: object
    properties:
      url:
        type: string
        format: uri
        description: Remote URL location of samplesheet
      script:
        type: string
        format: uri
        description: >-
          Path to script for converting downloaded sample metadata to
          CSV output. Script must take the downloaded file as input
          argument.

  species:
    description: Species name
    type: string
  sraruninfo:
    type: object
    description: SraRunInfo download configuration
    properties:
      filter:
        description: >-
          Apply qsv py filter to SraRunInfo file. Note that column
          names need to be provide in lower case.
        example: 'librarystrategy=="WGS" && samplename!="Assembly Plant"'
        type: string
  tsdate_options:
    type: string
    description: tsdate options
  tsinfer:
    sampleinfo_columns:
      type: string
      description: >-
        Comma-separated string of columns to be included in tsinfer
        sampleinfo file
    populations_columns:
      type: string
      description: >-
        Comma-separated string of columns to be included in tsinfer
        populations file


required:
  - bioproject
  - reference
  - species
